#!/bin/sh

# Ignore all flags
while getopts uL: flag; do true; done
shift $(($OPTIND - 1))

esc=$(printf '\033[')
wdiff -n -w "${esc}41;97m" -x "${esc}m" -y "${esc}1;103m" -z "${esc}m" "$@" | grep -F -C2 --color=never "$esc"
exec cmp -s "$@"
